# Generated by Django 2.2 on 2022-06-10 09:44

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='CategoryBrg',
            fields=[
                ('id_cat', models.AutoField(max_length=11, primary_key=True, serialize=False)),
                ('category', models.CharField(max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='TblBarang',
            fields=[
                ('id_barang', models.AutoField(max_length=11, primary_key=True, serialize=False)),
                ('nama_barang', models.CharField(blank=True, max_length=100, null=True)),
                ('harga_barang', models.CharField(blank=True, max_length=30, null=True)),
                ('created_at', models.DateField(auto_now_add=True)),
                ('code_brg', models.CharField(max_length=20)),
                ('updated_at', models.DateField(auto_now=True)),
                ('category', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='barang.CategoryBrg')),
            ],
        ),
    ]
