# Generated by Django 2.2 on 2022-06-20 14:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('barang', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='tblbarang',
            name='status',
            field=models.IntegerField(default=1),
        ),
    ]
