# Generated by Django 4.0.5 on 2022-07-02 11:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('barang', '0002_tblbarang_status'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tblbarang',
            name='id_barang',
            field=models.AutoField(primary_key=True, serialize=False),
        ),
    ]
