# Generated by Django 4.0.5 on 2022-07-02 11:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('barang', '0003_alter_tblbarang_id_barang'),
    ]

    operations = [
        migrations.AlterField(
            model_name='categorybrg',
            name='id_cat',
            field=models.AutoField(primary_key=True, serialize=False),
        ),
    ]
