# Generated by Django 5.2 on 2025-04-30 13:56

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0005_tentangkami2'),
    ]

    operations = [
        migrations.DeleteModel(
            name='TentangKami2',
        ),
    ]
