# Generated by Django 5.2 on 2025-04-30 14:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0006_delete_tentangkami2'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='tentangkami',
            name='id_tentangkami',
        ),
        migrations.AddField(
            model_name='tentangkami',
            name='id',
            field=models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
    ]
