# Generated by Django 5.2 on 2025-04-30 14:54

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0008_remove_tentangkami_id_tentangkami_id_tentangkami'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='visimisi',
            name='owner',
        ),
        migrations.DeleteModel(
            name='Ekstrakulikuler',
        ),
        migrations.DeleteModel(
            name='Visimisi',
        ),
    ]
