# Generated by Django 5.2 on 2025-04-30 15:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0009_remove_visimisi_owner_delete_ekstrakulikuler_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='prestasi',
            options={'ordering': ['-created_at'], 'verbose_name_plural': 'Prestasi'},
        ),
        migrations.RemoveField(
            model_name='prestasi',
            name='id_prestasi',
        ),
        migrations.AddField(
            model_name='prestasi',
            name='id',
            field=models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
        migrations.AddField(
            model_name='prestasi',
            name='slug',
            field=models.SlugField(blank=True, null=True, unique=True),
        ),
        migrations.AlterField(
            model_name='prestasi',
            name='desc',
            field=models.TextField(verbose_name='Deskripsi'),
        ),
        migrations.AlterField(
            model_name='prestasi',
            name='lokasi',
            field=models.CharField(max_length=255),
        ),
        migrations.AlterField(
            model_name='prestasi',
            name='nama',
            field=models.CharField(max_length=255),
        ),
        migrations.AlterField(
            model_name='prestasi',
            name='updated_at',
            field=models.DateTimeField(auto_now=True),
        ),
    ]
