# Generated by Django 5.2 on 2025-04-30 15:47

import ckeditor_uploader.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0010_alter_prestasi_options_remove_prestasi_id_prestasi_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='prestasi',
            options={'ordering': ['-created_at']},
        ),
        migrations.RemoveField(
            model_name='prestasi',
            name='desc',
        ),
        migrations.AddField(
            model_name='prestasi',
            name='content',
            field=ckeditor_uploader.fields.RichTextUploadingField(default=100),
            preserve_default=False,
        ),
    ]
