# Generated by Django 5.2 on 2025-04-30 16:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0011_alter_prestasi_options_remove_prestasi_desc_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='prestasi',
            name='slug',
            field=models.CharField(default=200, max_length=255),
            preserve_default=False,
        ),
    ]
