# Generated by Django 5.2 on 2025-05-08 08:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0012_alter_prestasi_slug'),
    ]

    operations = [
        migrations.CreateModel(
            name='SantriPendaftar',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nama', models.CharField(max_length=100)),
                ('nisn', models.CharField(max_length=10, unique=True)),
                ('tempat_lahir', models.CharField(max_length=100)),
                ('tanggal_lahir', models.DateField()),
                ('jenis_kelamin', models.CharField(choices=[('L', 'Laki-laki'), ('P', 'Perempuan')], max_length=10)),
                ('alamat', models.TextField()),
                ('nama_ayah', models.CharField(max_length=100)),
                ('nama_ibu', models.CharField(max_length=100)),
                ('no_hp', models.CharField(max_length=15)),
                ('email', models.EmailField(max_length=254)),
                ('foto', models.ImageField(blank=True, null=True, upload_to='media/images/pendaftar/')),
                ('tanggal_daftar', models.DateTimeField(auto_now_add=True)),
                ('status_verifikasi', models.BooleanField(default=False)),
                ('catatan_admin', models.TextField(blank=True, null=True)),
            ],
        ),
    ]
