# Generated by Django 5.2 on 2025-05-08 11:10

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0013_santripendaftar'),
    ]

    operations = [
        migrations.CreateModel(
            name='DataLengkapSantri',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('asal_sekolah', models.CharField(blank=True, max_length=150, null=True)),
                ('no_ijazah', models.CharField(blank=True, max_length=50, null=True)),
                ('golongan_darah', models.CharField(blank=True, max_length=3, null=True)),
                ('riwayat_penyakit', models.TextField(blank=True, null=True)),
                ('berat_badan', models.DecimalField(blank=True, decimal_places=2, max_digits=5, null=True)),
                ('tinggi_badan', models.DecimalField(blank=True, decimal_places=2, max_digits=5, null=True)),
                ('kebutuhan_khusus', models.CharField(blank=True, max_length=100, null=True)),
                ('nama_wali', models.CharField(blank=True, max_length=100, null=True)),
                ('hubungan_wali', models.CharField(blank=True, max_length=50, null=True)),
                ('no_hp_wali', models.CharField(blank=True, max_length=15, null=True)),
                ('penerima_kps', models.BooleanField(default=False)),
                ('no_kps', models.CharField(blank=True, max_length=50, null=True)),
                ('upload_kk', models.FileField(blank=True, null=True, upload_to='media/berkas/kk/')),
                ('upload_akte', models.FileField(blank=True, null=True, upload_to='media/berkas/akte/')),
                ('tanggal_dibuat', models.DateTimeField(auto_now_add=True)),
                ('tanggal_diupdate', models.DateTimeField(auto_now=True)),
                ('pendaftar', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='data_lengkap', to='home.santripendaftar')),
            ],
        ),
    ]
