"""
Django settings for pos project.

Generated by 'django-admin startproject' using Django 2.2.

For more information on this file, see
https://docs.djangoproject.com/en/2.2/topics/settings/

For the full list of settings and their values, see
https://docs.djangoproject.com/en/2.2/ref/settings/
"""

import os

# Build paths inside the project like this: os.path.join(BASE_DIR, ...)
BASE_DIR = os.path.dirname(os.path.dirname(os.path.abspath(__file__)))


# Quick-start development settings - unsuitable for production
# See https://docs.djangoproject.com/en/2.2/howto/deployment/checklist/

# SECURITY WARNING: keep the secret key used in production secret!
SECRET_KEY = '9pl1&*x2y2jif3!xk2ad2na2q4q)&v)bf%5_cuyk864t5h0k-g'

# SECURITY WARNING: don't run with debug turned on in production!
DEBUG = True

ALLOWED_HOSTS = []


# Application definition

INSTALLED_APPS = [
    'django.contrib.admin',
    'django.contrib.auth',
    'django.contrib.contenttypes',
    'django.contrib.sessions',
    'django.contrib.messages',
    'django.contrib.staticfiles',
    'crispy_forms',
    'crispy_bootstrap4',
    'home',
    'ckeditor',
    'ckeditor_uploader',
    'admin1',
    'account'
]
OPENAI_API_KEY = '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'
DEEPSEEK_API_KEY = "sk-b65cee49e25a4902b2a26f52b145f934"
OPENROUTER_API_KEY = "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"
GEMINI_API_KEY='AIzaSyAigKPjOa_ahTeRtKHFHLV2qUIBNhEd1lI'
MIDDLEWARE = [
    'django.middleware.security.SecurityMiddleware',
    'django.contrib.sessions.middleware.SessionMiddleware',
    'django.middleware.common.CommonMiddleware',
    'django.middleware.csrf.CsrfViewMiddleware',
    'django.contrib.auth.middleware.AuthenticationMiddleware',
    'django.contrib.messages.middleware.MessageMiddleware',
    'django.middleware.clickjacking.XFrameOptionsMiddleware',
]

ROOT_URLCONF = 'pos.urls'

TEMPLATES = [
    {
        'BACKEND': 'django.template.backends.django.DjangoTemplates',
        'DIRS': [BASE_DIR + '/templates',],
        'APP_DIRS': True,
        'OPTIONS': {
            'context_processors': [
                'django.template.context_processors.debug',
                'django.template.context_processors.request',
                'django.contrib.auth.context_processors.auth',
                'django.contrib.messages.context_processors.messages',
                'home.context_processors.ppdb_context'
            ],
        },
    },
]

WSGI_APPLICATION = 'pos.wsgi.application'


DATABASES = {
    'default': {
        'ENGINE': 'django.db.backends.sqlite3',
        'NAME': 'webinfo',
        # 'USER': 'postgres',
        # 'PASSWORD': 'tatam123',
        # 'HOST': 'localhost',
        # 'PORT': '5432',
    }
}


# Password validation
# https://docs.djangoproject.com/en/2.2/ref/settings/#auth-password-validators

AUTH_PASSWORD_VALIDATORS = [
    {
        'NAME': 'django.contrib.auth.password_validation.UserAttributeSimilarityValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.MinimumLengthValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.CommonPasswordValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.NumericPasswordValidator',
    },
]


# Internationalization
# https://docs.djangoproject.com/en/2.2/topics/i18n/

LANGUAGE_CODE = 'en-us'

TIME_ZONE = 'Asia/Jakarta'

USE_I18N = True

USE_L10N = True

USE_TZ = True

DEFAULT_AUTO_FIELD = 'django.db.models.AutoField'
CRISPY_TEMPLATE_PACK = 'bootstrap4'

LANGUAGE_CODE = 'id-idn'

TIME_ZONE = 'UTC'

USE_I18N = True

USE_L10N = True

USE_TZ = True
STATIC_URL = '/static/'

STATICFILES_DIRS =[
    BASE_DIR + "/static",
]
MEDIA_ROOT =  os.path.join(BASE_DIR, 'media') 
STATIC_ROOT =  os.path.join(BASE_DIR, 'stati') 
MEDIA_URL = '/media/'
import os


CKEDITOR_UPLOAD_PATH = 'uploads/'
FORM_RENDERER = 'django.forms.renderers.DjangoTemplates'
CKEDITOR_UPLOAD_PATH = 'uploads/'
CKEDITOR_FILENAME_GENERATOR = 'utils.get_filename'
CKEDITOR_UPLOAD_PATH = "uploads/"
CKEDITOR_IMAGE_BACKEND = 'pillow'
CKEDITOR_CONFIGS = {
    'default': {
        'toolbar': 'full',
        'height': 400,
        'width': 'auto',  # kita atur lebar lewat CSS agar responsif
        'extraPlugins': ','.join([
            'uploadimage', 'image2', 'autogrow'
        ]),
        # 'autoGrow_minHeight': 400,
        # 'autoGrow_maxHeight': 800,
        # 'autoGrow_onStartup': True,
        # 'removePlugins': 'resize',
    },
}

BOOTSTRAP4 = {
    'include_jquery': True,
}
CRISPY_TEMPLATE_PACK = 'bootstrap4'
from django.contrib.messages import constants as messages

MESSAGE_TAGS ={
    messages.DEBUG : 'alert-info',
    messages.INFO : 'alert-info',
    messages.ERROR : 'alert-danger',
    messages.SUCCESS : 'alert-success',
    messages.WARNING : 'alert-warning',
}

