# Generated by Django 5.2 on 2025-04-30 14:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('admin1', '0004_tentangkami2'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='tentangkami2',
            name='id_tentangkami2',
        ),
        migrations.AddField(
            model_name='tentangkami2',
            name='id',
            field=models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
    ]
