# Generated by Django 5.2 on 2025-05-06 16:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('admin1', '0006_visimisi'),
    ]

    operations = [
        migrations.CreateModel(
            name='SiteVisit',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('timestamp', models.DateTimeField(auto_now_add=True)),
                ('ip_address', models.GenericIPAddressField()),
            ],
        ),
    ]
